#!/usr/bin/env bash
# Install Nginx
sudo apt-get update
sudo apt-get install nginx

# Create a default index.html file
echo "Holberton School for the win!" > /var/www/html/index.html

# Restart Nginx
sudo service nginx restart

# Check the Nginx status code
curl -sI localhost | grep -q "200 OK"
